### ISSUE TITLE
Leave message loop.

### ISSUE THREAD

**Issue by XSlimeX** [Abhijith4124/Ahhh-Bot#1]
Hello! First of all, amazing job.
For some reason when i add a new server , it says "Failed To Add Server PALADIN. Check the Hostname and Port, also make sure the server is running... " even though it adds it and runs normally. 2nd issue is that the leave messages on restart of the server loop, if the server restarts, the bot will spam leave messages till i restart the bot.

![image](https://github.com/Abhijith4124/Ahhh-Bot/assets/49905629/fe2c21cb-eb80-42d1-b20b-357b299169b6)
this is the loop, the same people leaving over and over.

**Comment by zensi-dev** [comment]
Could you try the dev branch and let me know.

**Comment by XSlimeX** [comment]
> Could you try the dev branch and let me know.

wym? by the way i made the 
            
console.error(e);
        }
    }, 2000);
}
module.exports = {startRCONService}

to 10000 (10s). seems to make it a little bit better but still not a fix.

If you could explain how this works i maybe could find a solution for it. i believe the issue is in rconService.js though(for the loop problem at least).

my discord is: xmr.business if you wanna talk about it and help each other out. idk wym to create a dev branch about it xD

**Comment by zensi-dev** [comment]
I've made a dev branch and has been making changes and bug fixes on it, switch the branch from main to dev and test the bot.

https://github.com/Abhijith4124/Ahhh-Bot/tree/dev

**Comment by XSlimeX** [comment]
> I've made a dev branch and has been making changes and bug fixes on it, switch the branch from main to dev and test the bot.
> 
> https://github.com/Abhijith4124/Ahhh-Bot/tree/dev


I did, still same issue. 
edit: have you tried cleaning the db? i see it keeps the names there, make it clean if it cant connect to the server.

**Comment by zensi-dev** [comment]
It does clean the DB, but it should only add the data if the connection was successful. Could you try removing the server or clearing the entire data.json in data/data.json and try again?

**Comment by XSlimeX** [comment]
> It does clean the DB, but it should only add the data if the connection was successful. Could you try removing the server or clearing the entire data.json in data/data.json and try again?

clearing the whole data.json was a bad idea. I had to set up the server again. and yes i did both,didnt work.

does the clean script you added clean only the names or?

**Comment by XSlimeX** [comment]
It seems fixed now.
