### ISSUE TITLE
Just Steamid?

### ISSUE THREAD

**Issue by Blacky0316** [Abhijith4124/Ahhh-Bot#10]
Hello

You can also set that you only need the steamid for the whitelist otherwise it would be too complicated.
Because we are a very large discord server

Because you only get the PlayerUID when it is on the server joint and that is too complicated for large discord servers

**Comment by zensi-dev** [comment]
It just isn't that secure to whitelist with just SteamId or even the Game Player Uid alone. The bot will only kick the player after the character creation is done, that is when the Player Uid and Name gets assigned. If you are a large server, you can use the Whitelist Player Button provided underneath the Non Whitelist Player Kicked embed. With just a click you can whitelist the player.

Just make sure to setup the logs channel correctly using /serverconfig

**Comment by Blacky0316** [comment]
> It just isn't that secure to whitelist with just SteamId or even the Game Player Uid alone. The bot will only kick the player after the character creation is done, that is when the Player Uid and Name gets assigned. If you are a large server, you can use the Whitelist Player Button provided underneath the Non Whitelist Player Kicked embed. With just a click you can whitelist the player.
> 
> Just make sure to setup the logs channel correctly using /serverconfig

where can you set how often you should check whether someone is on the whitelist?

Because Discord likes to block things like that if you send commands too often.
Because we have 8 servers

**Comment by zensi-dev** [comment]
The Checking is Done every 5 Seconds and The status is updated on discord every 10 seconds.
Here is the part where the time interval for polling the server is used: https://github.com/Abhijith4124/Ahhh-Bot/blob/a310905de0296fc1dcfc0cc5315b0da8088e9a65/services/rconService.js#L456

Interval to update the status message: https://github.com/Abhijith4124/Ahhh-Bot/blob/a310905de0296fc1dcfc0cc5315b0da8088e9a65/services/rconService.js#L237

I don't think having 8 servers would be an issue. You could try the public hosted bot too using the add to server button in the readme.

**Comment by Blacky0316** [comment]
> Die Überprüfung erfolgt alle 5 Sekunden und der Status wird alle 10 Sekunden auf Discord aktualisiert. Hier ist der Teil, in dem das Zeitintervall für die Abfrage des Servers verwendet wird:
> 
> https://github.com/Abhijith4124/Ahhh-Bot/blob/a310905de0296fc1dcfc0cc5315b0da8088e9a65/services/rconService.js#L456
> 
> Intervall zur Aktualisierung der Statusmeldung:
> 
> https://github.com/Abhijith4124/Ahhh-Bot/blob/a310905de0296fc1dcfc0cc5315b0da8088e9a65/services/rconService.js#L237
> 
> Ich glaube nicht, dass es ein Problem wäre, 8 Server zu haben. Sie können auch den öffentlich gehosteten Bot ausprobieren, indem Sie in der Readme-Datei auf die Schaltfläche „Zum Server hinzufügen“ klicken.

I have already installed the server on an extra server myself

**Comment by Neoslyke** [comment]
What actually happen if the steam id changed but the uid stays the same? did they spoof?

**Comment by zensi-dev** [comment]
Sometimes their steam id only shows up partially. Seems like a game issue.
