### ISSUE TITLE
Where can I find a discord bot Token?

### ISSUE THREAD

**Issue by pakchee42** [Abhijith4124/Ahhh-Bot#11]
Hi I've created a Bot at https://discord.com/developers/applications and given it a badge. and added it to my Discord server, but I don't find that it can use commands like your Bot. How can I fix it? Thank you.

**Comment by pakchee42** [comment]
![node](https://github.com/Abhijith4124/Ahhh-Bot/assets/159820341/cbb32ac6-773d-4ace-9d4b-04d89458a3fe)

**Comment by zensi-dev** [comment]
Yea for some reason the bot does not register global commands well. I've made it to use Guild Commands instead. Try using the code from the dev branch.

**Comment by pakchee42** [comment]
Thanks, now I have a new problem.  Players who have already received
whitelist re-enter.  Your name will collide with other players, making you
unable to enter.

ในวันที่ จ. 19 ก.พ. 2024 02:37 น. Abhijith4124 ***@***.***>
เขียนว่า:

**Comment by pakchee42** [comment]
![image](https://github.com/Abhijith4124/Ahhh-Bot/assets/159820341/76a0a072-f1d5-4858-88b2-590abc00ce55)

**Comment by zensi-dev** [comment]
It might be their Steam Username, sometimes the game server returns their Steam name instead of the IGN. If they try to enter the  server again it should work fine.
