### ISSUE TITLE
Update ?

### ISSUE THREAD

**Issue by Blacky0316** [Abhijith4124/Ahhh-Bot#13]
how do I update to the new version?

**Comment by ShadyGame** [comment]
redownload i guess.

**Comment by zensi-dev** [comment]
@Blacky0316 if you used git clone, just using git pull should download the new files, else you can download the source code as zip and use that, don't forget to backup config.json and data/data.json files.

**Comment by Blacky0316** [comment]
> @Blacky0316 if you used git clone, just using git pull should download the new files, else you can download the source code as zip and use that, don't forget to backup config.json and data/data.json files.

I must again npm install make ? ....

**Comment by zensi-dev** [comment]
Yes, there are few new packages added
