### ISSUE TITLE
Rate limit api ban 

### ISSUE THREAD

**Issue by Blacky0316** [Abhijith4124/Ahhh-Bot#14]
Hello, I think your bot is not designed for multiple servers.
I have now received a discord api ban because I exceeded 50 requests per second.

because discord has a rate limit of 50 requests.

How many requests does your bot send on 1 server?

it is not good

**Comment by zensi-dev** [comment]
It should not hit the limit unless there is a lot of activity on the Game Server. There might also be a bug that can cause the bot to spam whitelist messages.

**Comment by Blacky0316** [comment]
> It should not hit the limit unless there is a lot of activity on the Game Server. There might also be a bug that can cause the bot to spam whitelist messages.

Each server has over 20 players.

but how many queries does the bot make when querying status, etc

**Comment by zensi-dev** [comment]
> > It should not hit the limit unless there is a lot of activity on the Game Server. There might also be a bug that can cause the bot to spam whitelist messages.
> 
> Each server has over 20 players.
> 
> but how many queries does the bot make when querying status, etc

The bot fetches data from the server every 5 seconds, that is when the new join/leave is checked as well as the whitelist.

The Server Status is Updated every 10 seconds.

You can see these values in rconService File.
