### ISSUE TITLE
Whitelist VIA IP Address

### ISSUE THREAD

**Issue by TheTargets** [Abhijith4124/Ahhh-Bot#2]
People are able to spoof their SteamID's and access the server with allows cheaters to ruin things

**Comment by zensi-dev** [comment]
The bot not only checks the SteamId but also the PlayerUID. This should make it a bit secure.

**Comment by TheTargets** [comment]
PlayerUID from Discord? I do think you should still add IP Address due to people still ruining fun

**Comment by zensi-dev** [comment]
Not from Discord, The Game generates a unique PlayerUID for the player when they create a character on the server. This PlayerUID will be logged by the bot to the log channel when a user tries to join. You can use this PlayerUID to whitelist the player. 

You can give the public bot a try using the Add to Server Button in the Readme and see if it works for you.
