### ISSUE TITLE
More discord alerts

### ISSUE THREAD

**Issue by doublee313** [Abhijith4124/Ahhh-Bot#20]
Awesome job on the bot. Very nice and professional. Thanks for fixing the latest update to work w/o whitelist.

Is it possible to add more alerts for discord? IE:

Treestyle shot Boar in the Body with their LR-300 Assault Rifle at a distance of 10.68 meters
Treestyle shot Scarecrow in the Head with their LR-300 Assault Rifle at a distance of 1.63 meters
Treestyle has just reached the rank of Airman

Levels ups, etc? This is nice to see what's going on in the game, etc. I have TRIBE LOGS plugins for ARK, etc. 

[Island](Nightcrawlers) [Day 1469][14:26]: Tribemember Slayer - Lvl 76 was killed by a Sabertooth - Lvl 168!
Tribe Logs
BOT
 — 02/24/2024 4:18 PM
[Island](Nightcrawlers) [Day 1469][17:32]: GREYGHOST50 (0002dcb198cc4508a812b7eac1d628d1) left this ARK!
Tribe Logs
BOT
 — 02/24/2024 4:34 PM
[Svart](Tribe of Seren) [Day 1309][06:06]: Drixyr Tamed a Colossal Spice Lunar Kentrosaurus - Lvl 361 (Colossal Spice Lunar Kentrosaurus)!

This is a feature request, not issue. Thanks.

**Comment by zensi-dev** [comment]
Currently this is not possible without a server side mod. This discord bot can access only the data available via RCON. There might be mods already that can achieve what you want.

**Comment by doublee313** [comment]
Thank you!
