### ISSUE TITLE
not working with new update

### ISSUE THREAD

**Issue by ShadyGame** [Abhijith4124/Ahhh-Bot#21]
Hi,

I think the bot stopped working with the latest patch 1.5.0 or its just mine?

**Comment by getteq** [comment]
> Hi,
> 
> I think the bot stopped working with the latest patch 1.5.0 or its just mine?

same to me, it's not working at all it needs to be updated

**Comment by getteq** [comment]
> Hi,
> 
> I think the bot stopped working with the latest patch 1.5.0 or its just mine?

In version v0.1.5.0 of the game server, RCONPort and RCONEnable in PalWorldSettings.ini do not take effect

Please add -RCONPort=25575 after ./PalServer.sh (Linux) or PalServer.exe (Windows) to enable

In server docker page there is a issue that rcon is not working by ini setting so I'll try a shot for it.

**Comment by getteq** [comment]
> Hi,
> 
> I think the bot stopped working with the latest patch 1.5.0 or its just mine?

It works! Basically this bug not caused by this docker but caused by palworld server's rcon's propagation method make sure your palworld server's rcon work properly.

**Comment by ShadyGame** [comment]
Yep it's working 

its not updating the status on discord. and it stops working sometimes
