### ISSUE TITLE
How to find playerUID add whitelist I don't know playerUID for new player to my server

### ISSUE THREAD

**Issue by porpytd** [Abhijith4124/Ahhh-Bot#22]
![Screenshot 2024-03-01 144328](https://github.com/Abhijith4124/Ahhh-Bot/assets/123675523/0019606a-7697-484b-b88f-09e7ae151c83)

**Comment by ShadyGame** [comment]
is the bot working for you?

**Comment by zensi-dev** [comment]
The PlayerUID should be there in the logs. You can also see the playerUID in game if you are an Admin
