### ISSUE TITLE
Send Gamelog in Thread.

### ISSUE THREAD

**Issue by boii** [Abhijith4124/Ahhh-Bot#24]
It's is possible Ahhh-Bot send message to Thread?

**Comment by zensi-dev** [comment]
Maybe, While inviting the bot give it the permission to send messages in a thread and it might work.

**Comment by boii** [comment]
> Maybe, While inviting the bot give it the permission to send messages in a thread and it might work.

Already invite bot in Thread but in /serverconfig only can select Channel, Thread not show.

![image](https://github.com/Abhijith4124/Ahhh-Bot/assets/972204/1cf66748-7aca-4595-ac39-e781a4d71431)

**Comment by zensi-dev** [comment]
Yea, then i guess it's not possible to use threads at the moment
