### ISSUE TITLE
cant add my server, idk why

### ISSUE THREAD

**Issue by AbangMB** [Abhijith4124/Ahhh-Bot#25]
this things is new for me, so maybe i do something wrong, pls help. 
i already run the bot its online, i run the server using node js that i run in cmd just like the readme told me i install pm2 and run pm2 index.js, i already set the config file, the bot is online, i can run the command but the problem is when i try to add the server it always say it fail, maybe my server is the problem. but, when i use palbot. it can add the server and it work normaly. can anyone help me, thank u.
![image](https://github.com/Abhijith4124/Ahhh-Bot/assets/75205356/65f91e3a-389d-471d-8fd2-e00c305f592e)
![image](https://github.com/Abhijith4124/Ahhh-Bot/assets/75205356/e9fe7302-2464-4356-b2f9-fe655eb96e74)

**Comment by BloodDragon2580** [comment]
i Have the same problem
