### ISSUE TITLE
Cannot remove whitelist

### ISSUE THREAD

**Issue by jingwuk** [Abhijith4124/Ahhh-Bot#27]
the addwhitelist feature did work, but when i try to remove the whitelist, it said that Player is not whitelisted
Parameter playername doesnt show option, it only shows Loading Option Failed

**Comment by zensi-dev** [comment]
Could you try entering the player name manually?

**Comment by jingwuk** [comment]
I did, but still didnt work, but i problably know the reason
so when add  another server with the same bot, it does add the whitelist,
though i think the whitelist didnt recognize which server is it,

when ive added it, maybe it goes to the wrong one, eventhough i did put the correct server,
so when i try to remove it, it shows that theres no user with that name in the whitelist

i did remove my whitelist through the db, but i didnt test the thing, because my other server dont have the whitelist feature turned on
