### ISSUE TITLE
slash commands do not work !

### ISSUE THREAD

**Issue by BigglesDevs** [Abhijith4124/Ahhh-Bot#30]

**Comment by BigglesDevs** [comment]
When im trying to do the /commands it dose not works says interaction failed

**Comment by zensi-dev** [comment]
Are you using the public bot or self hosted?

**Comment by BigglesDevs** [comment]
self hosted

**Comment by Korivash** [comment]
Self hosted, most slash commands do not work. 

Here are the ones that do work however.

/serverconfig: Displays options to configure your Palworld Server within the Discord Server.
Configuration Options:
Gamelog Channel: Set a channel to receive game logs such as player join/leave events.
Status Channel: Set a channel for server status updates.
Whitelist Announcement Channel: Set a channel for whitelist announcements.
Whitelist Log Channel: Set a channel for whitelist logs.
Whitelist Role: Assign a role to whitelisted users.
Managing Palworld Servers
/addpalserver: Add a Palworld Server by providing server details.
/listpalservers: View the list of added Palworld Servers.
/removepalserver [server]: Remove a previously added Palworld Server.
Whitelisting Players
/whitelist [server] [enabled]: Enable or disable whitelist for a Palworld Server.
/addwhitelist [server] [steamid] [playeruid] [discorduser]: Add a player to the whitelist. Optionally, mention the Discord user for role assignment and announcement.
/removewhitelist [server] [playername] [discorduser]: Remove a player from the whitelist. Optionally, mention discord user to remove associated Discord roles.
-/linkwhitelist [server] [playername] [discorduser]: Links a Game Player to a Discord User, granting them Whitelist roles and Welcome message if specified.
-/unlinkwhitelist [server] [playername]: Unlinks a Game Player from a Discord User, removes thier Whitelist roles if specified.
Miscellaneous Commands
/save: Save the current Palworld game state.
/broadcast [server] [message]: Send a message to players on the Palworld Server.
/banplayer [server] [playersteamid]: Ban a player by their Steam ID.
/kickplayer [server] [playersteamid]: Kick a player by their Steam ID.

**Comment by zensi-dev** [comment]
All the mentioned commands work fine, i've tested it and others have tested as well. Check if you've setup the bot properly
