### ISSUE TITLE
bug?

### ISSUE THREAD

**Issue by Chok-Dev** [Abhijith4124/Ahhh-Bot#8]
![Screenshot 2024-02-14 190625](https://github.com/Abhijith4124/Ahhh-Bot/assets/80238446/1abc0c7d-c0fb-49a2-ac62-4ca4c3e3cfc5)
![Screenshot 2024-02-14 190838](https://github.com/Abhijith4124/Ahhh-Bot/assets/80238446/16511dd6-34fc-43d9-9ba5-c0c20d7a6dcc)

**Comment by Chok-Dev** [comment]
![image](https://github.com/Abhijith4124/Ahhh-Bot/assets/80238446/d0b7c972-6cc7-4361-aa45-7be25ee58439)

**Comment by zensi-dev** [comment]
Yea this is currently a bug, testing out ways to resolve it

**Comment by Chok-Dev** [comment]
ok keep fighting Good bot

**Comment by zensi-dev** [comment]
This issue has been resolved in the dev branch. Testing currently on the public bot to see if it happens again.
