### ISSUE TITLE
Suggestion: Playtime tracking & profile command

### ISSUE THREAD

**Issue by voicecodee** [Abhijith4124/Ahhh-Bot#9]
Add option for owner of the profile to do /profile to see their playtime on server. Track time start via join, Track time stop via leave or server crash or restart. Would be a good gauge to identify cheat players from their playtime too.

Scheduled server restarts with broadcast 5 min before restart, countdown broadcast till restart, in 1 min intervals.
A /broadcast and /shutdown command will do since a crash scheduler can be setup on the server manager to restart every time the process is down.

**Comment by zensi-dev** [comment]
Thanks for the suggestions. These are possible features but require upgrading the the basic json db strructure. Once the current bugs are fixed i will work on reliability and then add new features.
